## ------------------------------------------- Mock ID Integration properties ------------------------------------------------------------
#mosip.certify.integration.scan-base-package=io.mosip.certify.mock.integration
mosip.certify.integration.scan-base-package=io.mosip.certify.peruiddataprovider.integration
mosip.certify.integration.audit-plugin=LoggerAuditService
mosip.certify.integration.vci-plugin=MockVCIssuancePlugin

## ------------------------------------------- Mock ID plugin related properties ------------------------------------------------------------
mosip.certify.mock.vciplugin.verification-method=${mosip.certify.authn.jwk-set-uri}
mosip.certify.mock.authenticator.get-identity-url=http://mock-identity-system:8082/v1/mock-identity-system/identity
mosip.certify.cache.security.algorithm-name=AES/ECB/PKCS5Padding
mosip.certify.cache.secure.individual-id=false
mosip.certify.cache.store.individual-id=true


mosip.certify.data-provider-plugin.issuer-uri=did:web:peru-id.github.io:inji-config:Reniec-Peru
mosip.certify.data-provider-plugin.issuer-public-key-uri=did:web:peru-id.github.io:inji-config:Reniec-Peru#key-0

## ------------------------------------------- UseCase specific default overriding properties ------------------------------------------------------------
mosip.certify.domain.url=https://${mosip.injicertify.mock.host:${mosip.injicertify.host}}
mosip.certify.identifier=${mosip.certify.domain.url}
mosip.certify.authorization.url=https://${mosip.esignet.mock.host}
mosip.certify.database.name=inji_certify_mock
# conditionally set the SOFTHSM pin based on the setup requirements and fallback to the latter if former value is missing
mosip.kernel.keymanager.hsm.keystore-pass=${softhsm.certify.mock.security.pin:${softhsm.certify.security.pin}}


mosip.certify.peru-id.data-provider-plugin.nu-dni-usuario=44298478
mosip.certify.peru-id.data-provider-plugin.nu-ruc-usuario=20295613620
mosip.certify.peru-id.data-provider-plugin.password=44298478
mosip.certify.peru-id.data-provider-plugin.endpoint-uri=http://65.1.93.129/consultadnie/ConsultaDniService

mosip.certify.plugin-mode=DataProvider
mosip.certify.data-provider-plugin.id-field-prefix-uri=https://mosip.io/credential/
mosip.certify.integration.data-provider-plugin=PeruIdentityDataProviderPlugin
mosip.certify.data-provider-plugin.issuer.vc-sign-algo=Ed25519Signature2020
## CSV specific config
mosip.certify.mock.data-provider.csv.identifier-column=id
mosip.certify.mock.data-provider.csv.data-columns=id,firstName,firstSurName,secondSurName,dateOfBirth,gender,maritalStatus,face
mosip.certify.mock.data-provider.csv-registry-uri=/home/mosip/config/farmer_identity_data.csv
mosip.certify.data-provider-plugin.rendering-template-id=
mosip.certify.key-values={\
  'latest' : {\
              'credential_issuer': '${mosip.certify.identifier}',   \
              'authorization_servers': {'${mosip.certify.authorization.url}'}, \
              'credential_endpoint': '${mosip.certify.domain.url}${server.servlet.path}/issuance/credential', \
              'display': {{'name': 'DNI Digital', 'locale': 'es'}},\
              'credential_configurations_supported' : { \
                 'ReniecCredential' : {\
                    'format': 'ldp_vc',\
                    'scope' : 'mock_identity_vc_ldp',\
                    'cryptographic_binding_methods_supported': {'did:jwk'},\
                    'credential_signing_alg_values_supported': {'Ed25519Signature2020'},\
                    'proof_types_supported': {'jwt': {'proof_signing_alg_values_supported': {'RS256', 'PS256'}}},\
                    'credential_definition': {\
                      'type': {'VerifiableCredential','ReniecCredential'},\
                      'credentialSubject': {\
                            'firstName': {'display': {{'name': 'Prenombres','locale': 'es'}}}, \
                            'firstSurName': {'display': {{'name': 'Primer Apellido','locale': 'es'}}}, \
                            'secondSurName': {'display': {{'name': 'Segundo Apellido','locale': 'es'}}}, \
                            'dateOfBirth': {'display': {{'name': 'Fecha Nacimiento','locale': 'es'}}},\
                            'gender': {'display': {{'name': 'Genero','locale': 'es'}}},\
                            'maritalStatus': {'display': {{'name': 'Apellido Casada','locale': 'es'}}}\
                    }},\
                    'display': {{'name': 'DNI Digital', \
                                  'locale': 'es', \
                                  'logo': {'url': 'https://peru-id.github.io/inji-config/Logo/Reniec.JPG','alt_text': 'logo of a Reniec'},\
                                  'background_color': '#FDFAF9',\
                                  'background_image': { 'uri': 'https://peru-id.github.io/inji-config/Logo/Reniec.JPG' }, \
                                  'text_color': '#7C4616'}},\
                    'order' : {'firstName','firstSurName','secondSurName','dateOfBirth','gender','maritalStatus'}\
              }}}}
